#!/bin/sh
#
# 2011 Steven Armstrong (steven-cdist at armstrong.cc)
# 2012-2014 Nico Schottelius (nico-cdist at schottelius.org)
# 2014 Daniel Heule     (hda at sfs.biz)
#
# This file is part of cdist.
#
# cdist is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# cdist is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with cdist. If not, see <http://www.gnu.org/licenses/>.
#


state_is="$(cat "$__object/explorer/state")"

if [  "$state_is" = "present" ]; then
    exit 0
fi

# check whether the states match
case "$state_is" in
    	absent)
	    echo "insert" >> "$__messages_out"
	;;
        *)
            echo "Unknown explorer state: $state_is" >&2
            exit 1
        ;;
esac

cat "$__type/files/remote_script.sh"
